services:
  node:
    image: node:22-alpine
    user: node
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development